# Generated by Django 2.1.5 on 2019-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_news',
            name='publieshed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date publieshed'),
        ),
    ]
