# Generated by Django 2.1.5 on 2019-03-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_blog_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=50)),
                ('categories_summary', models.CharField(max_length=200)),
                ('urls_slung_category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('urls_slung_inf', models.CharField(default='default', max_length=30)),
                ('news_catagory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainapp.Category')),
            ],
        ),
        migrations.AddField(
            model_name='blog_news',
            name='urls_slung',
            field=models.CharField(default='new_news', max_length=30),
        ),
    ]
